version: "3"
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
services:  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./data:/prometheus
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
  app:
    container_name: app
    build: ./flask_api/.
    ports:
      - 5000:5000
    volumes:
      - ./flask_api/app.py:/app.py

