global:
 scrape_interval:     15s
 evaluation_interval:  15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']