global:
 scrape_interval:     15s
 evaluation_interval:  15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      #- targets: ['app:5000']
      - targets: ['prometheus:9090']
    metrics_path: '/metrics'
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  
  - job_name: 'nginx'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]